import { createClient, type GenericCtx, type ComponentApi } from "@convex-dev/better-auth";
import { convex } from "@convex-dev/better-auth/plugins";
import { type DataModel } from "./_generated/dataModel";
import { query } from "./_generated/server";
import { betterAuth } from "better-auth";
import authConfig from "./auth.config";

const siteUrl = process.env.SITE_URL!;

// The component client has methods needed for integrating Convex with Better Auth,
// as well as helper methods for general use.
// Note: components.betterAuth will be generated by Convex codegen once deployed
// For now, we'll use a type assertion to work around the missing generated types
import type { components as ComponentsType } from "./_generated/api";
declare module "./_generated/api" {
  export interface components {
    betterAuth: ComponentApi<"betterAuth">;
  }
}

export const authComponent = createClient<DataModel>(
  (undefined as ComponentsType).betterAuth as any,
);

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth({
    baseURL: siteUrl,
    database: authComponent.adapter(ctx),
    // Configure simple, non-verified email/password to get started
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: false,
    },
    plugins: [
      // The Convex plugin is required for Convex compatibility
      convex({ authConfig }),
    ],
  });
};

// Example function for getting the current user
// Feel free to edit, omit, etc.
export const getCurrentUser = query({
  args: {},
  handler: async (ctx) => {
    return authComponent.getAuthUser(ctx);
  },
});
